class Parent {

    Parent() {
        System.out.println("Parent class 0-arg Constructor");
    }
}

class Child extends Parent {

    Child() {
        // super(); generated by compiler
        System.out.println("Child class 0-arg Constructor");
    }

    Child(int a) {
        // super(); generated by compiler
        System.out.println("Child class 1-arg Constructor");
    }
}

public class SuperThisConstructorCall2 {
    public static void main(String[] args) {
        new Child();
        new Child(10);
    }
}

