class Parent {
	// Instance block
	{
		System.out.println("Super-class instance block");
	}

	// Constructor
	Parent() {
		System.out.println("Super-class 0-arg constructor");
	}
}

public class Child1 extends Parent {
	// Instance block
	{
		System.out.println("Sub-class instance block");
	}

	// Constructor
	Child1() {
		// super(); // Generated by compiler
		System.out.println("Sub-class 0-arg constructor");
	}

	// Main method
	public static void main(String[] args) {
		new Child1();
	}
}

/*
 * Output:- 
 * Super-class instance block
 * Super-class 0-arg constructor
 * Sub-class instance block
 * Sub-class o-arg constructor
 */
